apiVersion: v1
kind: Pod
metadata:
  name: test-spark-dbt
  namespace: lakehouse
spec:
  volumes:
    - name: dbt-project-storage
      emptyDir:
        sizeLimit: 2Gi
    - name: tmp-storage
      emptyDir:
        sizeLimit: 3Gi
  initContainers:
    - name: "clone-dbt-repo"
      image: "alpine/git"
      command: ["sh", "-c"]
      args: ["git clone --depth=1 --branch master https://oauth2:<PAT>@git.cads.live/data-engineers/dbt-tracking.git /dbt_project"]
      volumeMounts:
        - mountPath: "/dbt_project"
          name: "dbt-project-storage"
  containers:
    - name: my-interactive-container
      image: python:3.11-slim
      command: ["bash", "-c"]
      args:
        - |
          pip install --no-cache-dir pyspark 'dbt-spark[session]' dbt-core pandas pyarrow numpy grpcio grpcio-status &&
          echo "Setup complete. Container is ready for exec." &&
          sleep infinity
      env:
        - name: http_proxy
          value: "proxy.hcm.fpt.vn:80"
        - name: https_proxy
          value: "proxy.hcm.fpt.vn:80"
        - name: SPARK_CONNECT_URL
          value: "sc://binhln.cads.live:80"
        - name: DBT_PROFILES_DIR
          value: "/dbt_project/.dbt"
        - name: HOME
          value: /tmp
        - name: DBT_PROFILES_DIR
          value: "/dbt_project/tracking_behavior/.dbt"
        - name: PATH
          value: "/tmp/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      volumeMounts:
        - mountPath: "/dbt_project"
          name: "dbt-project-storage"
        - mountPath: "/tmp"
          name: "tmp-storage"
      resources:
        requests:
          cpu: "250m"
          memory: "512Mi"
          ephemeral-storage: "1Gi"
        limits:
          cpu: "1"
          memory: "3Gi"
          ephemeral-storage: "3Gi"
  hostAliases:
    - ip: "172.24.177.51"
      hostnames:
        - "binhln.cads.live"
  restartPolicy: Never