apiVersion: spark.apache.org/v1beta1
kind: SparkApplication
metadata:
  name: spark-connect-server
spec:
  mainClass: "org.apache.spark.sql.connect.service.SparkConnectServer"
  sparkConf:
    spark.master: "k8s://https://lb-apiserver-dev.kubernetes-dev.local:8443" # Run kubectl cluster-info to get info
    spark.deployMode: "cluster"
    spark.executor.cores: "1"
    spark.cores.max: "3"
    spark.kubernetes.authenticate.driver.serviceAccountName: "spark"
    spark.kubernetes.container.image: "apache/spark:4.0.0"
    spark.ui.reverseProxy: "true"
    spark.sql.connect.grpc.binding: "0.0.0.0:15002"
    # config hdfs
    spark.hadoop.fs.defaultFS: "hdfs://namenode:8020"
    spark.sql.catalogImplementation: "hive"
    spark.hadoop.hive.metastore.uris: "thrift://hive-metastore:9083"
    # config s3
    spark.hadoop.fs.s3a.endpoint: "https://s3.amazonaws.com"
    spark.hadoop.fs.s3a.access.key: "YOUR_ACCESS_KEY"
    spark.hadoop.fs.s3a.secret.key: "YOUR_SECRET_KEY"
    spark.hadoop.fs.s3a.impl: "org.apache.hadoop.fs.s3a.S3AFileSystem"
    spark.hadoop.fs.s3a.path.style.access: "true"
    # config delta
    spark.sql.extensions: "io.delta.sql.DeltaSparkSessionExtension"
    spark.sql.catalog.spark_catalog: "org.apache.spark.sql.delta.catalog.DeltaCatalog"
    # config iceberg
    spark.sql.catalog.my_catalog: "org.apache.iceberg.spark.SparkCatalog"
    spark.sql.catalog.my_catalog.type: "hadoop"
    spark.sql.catalog.my_catalog.warehouse: "s3a://my-bucket/iceberg/"
  runtimeVersions:
    sparkVersion: "4.0.0"
  driverSpec:
    podTemplateSpec:
      spec:
        containers:
         - ports:
            - protocol: TCP
              containerPort: 15002
  driverServiceIngressList:
    - serviceMetadata:
        name: "spark-connect-service"
      serviceSpec:
        ports:
          - protocol: TCP
            port: 15002
            targetPort: 15002
      ingressMetadata:
        name: "spark-connect-ingress"
        annotations:
          nginx.ingress.kubernetes.io/backend-protocol: "GRPC"
---
apiVersion: v1
kind: Service
metadata:
  name: spark-connect-service
  namespace: lakehouse
spec:
  type: ClusterIP
  selector:
    spark-app-selector: spark-connect-server-0
  ports:
    - name: connect-port
      port: 15002
      targetPort: 15002
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: spark-connect-ingress
  namespace: lakehouse
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "GRPC"
spec:
  ingressClassName: nginx
  rules:
    - host: dev-cadshouse.cads.live
      http:
        paths:
          - path: /binhln
            pathType: Prefix
            backend:
              service:
                name: spark-connect-service
                port:
                  number: 15002